// svg
import clear_sky_d from '../img/clear-sky-d.svg';
import clear_sky_n from '../img/clear-sky-n.svg';
import few_clouds_d from '../img/few-clouds-d.svg';
import few_clouds_n from '../img/few-clouds-n.svg';
import clouds_d from '../img/clouds-d.svg';
import clouds_n from '../img/clouds-n.svg';
import broken_clouds_d from '../img/broken-clouds-d.svg';
import broken_clouds_n from '../img/broken-clouds-n.svg';
import shower_rain_d from '../img/shower-rain-d.svg';
import shower_rain_n from '../img/shower-rain-n.svg';
import rain_d from '../img/rain-d.svg';
import rain_n from '../img/rain-n.svg';
import thunder_d from '../img/thunder-d.svg';
import thunder_n from '../img/thunder-n.svg';
import snow_d from '../img/snow-d.svg';
import snow_n from '../img/snow-n.svg';
import mist_d from '../img/mist-d.svg';
import mist_n from '../img/mist-n.svg';

export const getIcon = (icon) => {
  if (icon === '01d') return clear_sky_d;
  else if (icon === '01n') return clear_sky_n;
  else if (icon === '02d') return few_clouds_d;
  else if (icon === '02n') return few_clouds_n;
  else if (icon === '03d') return clouds_d;
  else if (icon === '03n') return clouds_n;
  else if (icon === '04d') return broken_clouds_d;
  else if (icon === '04n') return broken_clouds_n;
  else if (icon === '09d') return shower_rain_d;
  else if (icon === '09n') return shower_rain_n;
  else if (icon === '10d') return rain_d;
  else if (icon === '10n') return rain_n;
  else if (icon === '11d') return thunder_d;
  else if (icon === '11n') return thunder_n;
  else if (icon === '13d') return snow_d;
  else if (icon === '13n') return snow_n;
  else if (icon === '50d') return mist_d;
  else if (icon === '50d') return mist_n;
  else return mist_n;
};
